"use client";
import {
  Box,
  Container,
  Heading,
  Image,
  SimpleGrid,
  Stack,
  Text,
} from "@chakra-ui/react";
import { useEffect, useState } from "react";

interface Props {
  children: React.ReactNode;
}

const imageURLs = [
  "https://contents.kikito.docomo.ne.jp/contents/devices/GP000790/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/GP000791/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/GP000421/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/GP000700/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/GP000701/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/GP000792/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/GP000600/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/GP000601/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/GP000621/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/GP000690/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/IN000900/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/IN001500/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/IN000400/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/IN000110/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/IN000500/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/IN000600/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/IN001000/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/IN001190/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/IN001191/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/IN001290/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/IN001291/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/IN000310/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/IN000311/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/RI000400/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/RI000210/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/RI000211/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/RI000220/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/RI000110/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/RI000111/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/GP000310/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/GP000311/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/IN000701/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/IN000700/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/IN000702/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/IN000703/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/IN000721/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/IN001300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/IN001301/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/IN001302/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/ZR000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/PA002100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/PA003900/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/PA000510/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/JV000210/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/JV000110/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO002800/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO003100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO001200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO001000/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO001020/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/CA000310/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/CA000410/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO003500/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO003600/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO003400/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO000110/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/NK000110/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/PA004700/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/PA004800/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/PA005100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/PA000110/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/CA001700/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/CA001600/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/CA001200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/CA001300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/CA001900/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/CA002000/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SM000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/CA000810/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/CA001010/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/CA000910/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/CA000710/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/CA000411/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/CA000111/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO000310/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO000410/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO003201/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO002900/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO000411/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/CA001801/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/CA001400/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/CA001500/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/FJ000110/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/OL000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/OL000101/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/RI000600/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/RI000500/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/RI000520/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/MZ000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/IN000800/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/MZ000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/FJ000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/AK002300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/PT000110/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/PT000500/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/HT000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO001100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/NR000290/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/NR000291/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/NR000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/NR000201/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/NR000300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/NR000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/NR000102/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/NR000103/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/NR000190/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/NR000192/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/TC000300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/TC000301/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/TC000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/TC000201/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/DO000190/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/DO000390/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/DO000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/DO000300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/VI000102/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/VI000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/VI000101/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/TC000400/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/VI000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/VI000201/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/VI000202/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/VI000203/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/PI000490/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/PI000590/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/PI000491/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/PI000400/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/PI000300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/PI000301/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/PI000401/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/PI000492/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/PI000110/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/EP000900/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/EP001000/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/EP000110/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/EP000120/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/EP000310/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/EP000210/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/EP000220/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/EP000410/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/AK000700/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/AK000500/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/AK000310/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/BQ000110/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/BQ000120/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/XG000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/AK002090/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/AK001290/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/AK002290/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/AK001590/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/AK001200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/AK000600/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/AK000400/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/AK000210/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/AK000110/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/AK000120/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/PI000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/FC000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/FC000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/FC000300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/BQ000500/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/BQ000600/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/BQ000400/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/BQ000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/CA001100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/AM000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/AC000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SG000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/XG000300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/XG000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/UN000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO001300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO004100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO004400/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO001400/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO001500/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO000910/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/MS000110/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/BX000110/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/AF000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/BO000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/BO000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/AF000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/AF000300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO002400/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO002401/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/DY000900/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/NS000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/BS000210/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/AK000800/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/AK000900/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO004200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO001600/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO000610/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO003900/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO000710/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO000810/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO003700/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO003800/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO002200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO002100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO002300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/YH000300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO001800/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/YH000500/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/YH000600/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/YH000401/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/YH000400/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SN000210/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/DK000500/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/DK000600/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/DK000400/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/DK000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/DK000300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SH002600/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SH002700/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SH003400/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SH003500/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SH003390/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SH001390/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SH000500/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SH000400/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/MX000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/BL000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/CD000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/CD000600/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/CD000700/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/KR000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/LG000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/AD000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/AD000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/VS000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/MD000300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/QR000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/QR000101/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/QR000190/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/MM000201/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/MM000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/MM000101/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/MM000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SB000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SB000300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SH003600/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/MI000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SH002200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/MI000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/CD000400/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/PA005600/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SH003700/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/PA001400/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SH002100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SH002300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SR000300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SR000400/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/CD000300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SR000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/HI000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/BA000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/CD000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/DY001300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/PA005500/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/DY000700/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/PA003500/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/KR000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/DY000300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SR000500/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/YZ000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/RH000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SR000600/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/IS000700/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/IS000300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/IS000500/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/IS000400/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/HI000700/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SH001400/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/CD000900/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/FE000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/FE000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/IS000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/IS000120/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/BR000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/JA000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/JA000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SI000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/DE000400/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/DE000300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/DE000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/DE000120/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/DE000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/DK000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SH002800/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/DI000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/MM000500/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/MM000300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/MM000400/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/PH000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/MK000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/MK000500/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/PA005400/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/PA002900/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/MD000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/ZO000300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/ZO000400/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/PA004600/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SH003100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/MK001300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/AK002500/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/MK002200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/MD000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/KJ000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/WT000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/YM000600/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/YM000110/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/YM000111/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/YM000310/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/KI000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/CO000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/PA002300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/GM000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/GM000290/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/GM000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/GM000190/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/YM000400/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/PA000900/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/YM000500/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/OH000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/FM000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/AT000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/FM000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/DA000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/HY000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/MY000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/HY000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/CD000800/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/GA000710/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/GA000810/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/GA000310/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/GA000410/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/GA000110/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/GA000210/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/GA001100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/GA000610/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/GA001500/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/GA001600/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/GA000900/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/GA001000/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/GA001200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/GA001300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/GA001700/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/GA001400/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/FI000400/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/FI000210/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/FI000600/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/FI000300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/FI000110/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/FI000500/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SC000500/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SC000600/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/FU000300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/FU000110/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/FU000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/KN000300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/BR000300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/BF000501/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/BF000600/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/BF000601/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/BF000400/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/BF000401/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/BF000300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/BF000301/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/BF000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/NP000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/NP000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/EP000700/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/EP000600/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/EP000800/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/EP000500/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/FJ000400/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/FJ000300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/BR000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/CA002200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/CA002100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/EP001100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/BF000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/BF000201/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/FU000400/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/NP000400/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/AK001000/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/IN001400/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/EL000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/PF000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/PF000300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/PF000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/RF000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/RF000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/NS000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/MS000300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/MS000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/CR000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/WC000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SD000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SD000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/BK000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/CS000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/CS000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/CS000300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/NP000300/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO002000/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/RA000100/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/RA000200/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO002001/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/SO003000/thumbnail/thumbnail.png",
  "https://contents.kikito.docomo.ne.jp/contents/devices/TT000100/thumbnail/thumbnail.png",
];

// 配列をシャッフルする関数
const shuffleArray = (array: string[]) => {
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
  }
  return array;
};

// ランダムに12枚の画像を選ぶ関数
const getRandomImages = (imageURLs: string[]) => {
  const shuffled = shuffleArray([...imageURLs]); // 配列をコピーしてシャッフル
  return shuffled.slice(0, 12); // 最初の12枚を返す
};

const ImageGrid = () => {
  const [images, setImages] = useState<string[]>([]);

  // ランダムに12枚の画像を取得してセットする関数
  const updateImages = () => {
    const selectedImages = getRandomImages(imageURLs);
    setImages(selectedImages);
  };

  // 初期化処理と3秒ごとの画像更新
  useEffect(() => {
    // 初回の画像セット
    updateImages();

    // 3秒ごとに画像を更新
    const intervalId = setInterval(() => {
      updateImages();
    }, 3000);

    // クリーンアップ関数でintervalを解除
    return () => clearInterval(intervalId);
  }, []);

  return (
    <Box py={12} bg={"gray.100"}>
      <Container maxW="3xl">
        <Stack spacing={2} textAlign={"center"}>
          <Heading as="h1" fontSize="4xl">
            商品ラインナップ
          </Heading>
          <Text fontSize="lg" color={"gray.500"}>
            最新商品から人気商品まで品揃え
          </Text>
        </Stack>
        <SimpleGrid my={10} columns={{ sm: 3, md: 4 }} spacing={6}>
          {images.map((imageURL, index) => (
            <Box key={index}>
              <Image
                src={imageURL}
                alt={`image-${index}`}
                style={{ width: "100%", height: "auto" }}
              />
            </Box>
          ))}
        </SimpleGrid>
      </Container>
    </Box>
  );
};

export default ImageGrid;
